.TH IVM 6 2013-04-16

.SH NAME
\fBivm\fP \- Humorous typo-based vim runner; drives a car over the terminal.

.SH DESCRIPTION
\fBivm\fP is intended to catch accidental typos of 'ivm' instead of 'vim'. It
displays an animation of a car driving by, and then launches vim. Any
parameters or arguments given to \fBivm\fP will be passed through to vim.

The car image is derived from the look of an old VW Golf IVM.

.SH ENVIRONMENT
.TP
.B VIM
\fBivm\fP respects the
.RB $ VIM
environment variable. If VIM is set, its value will
be used to launch vim after the animation finishes, instead of searching for
vim in your PATH.
.TP
.B IVM_SPEED
If
.RB $ IVM_SPEED
is set to a parsable integer, its value is used to control the speed of the
animation.


.SH SEE ALSO
\fBvim\fP(1), \fBsl\fP(6)

.SH AUTHOR
\fBivm\fP was written by Richard Wossal <richard@r-wos.org>. This manual was
written by Felix Crux <felixc@felixcrux.com> for the Debian project, but may
be used by others under the same terms as \fBivm\fP itself.
